[package]
name = "rust-mmsd"
version = "0.1.0"
authors = ["ArenM <aren@peacevolution.org>"]
edition = "2018"

[workspace]
members = ["mms-parser"]

[dependencies]
structopt = "0.3"
isahc = "0.9.12"
mms-parser = { path = "./mms-parser" }
