[package]
name = "mms-parser"
version = "0.1.0"
authors = ["ArenM <aren@peacevolution.org>"]
edition = "2018"

[lib]
name = "mms_parser"

[dependencies]
clap = "2.33.3"
nom = "5.1.2"
log = "0.4.11"
env_logger = "0.7.1"
