[package]
name = "mms-parser"
version = "0.1.0"
authors = ["ArenM <aren@peacevolution.org>"]
edition = "2018"

[lib]
name = "mms_parser"

[dependencies]
pico-args = "0.3.4"
nom = "5.1.2"
log = "0.4.11"
num-bigint = "0.3"

# TODO: this is only needed for the bin target
simple_logger = "1.9.0"
