[package]
name = "mms-parser"
version = "0.1.0"
authors = ["ArenM <aren@peacevolution.org>"]
edition = "2018"

[lib]
name = "mms_parser"

[[bin]]
name = "paraser"
path = "src/main.rs"

[dependencies]
pico-args = "0.3.4"
nom = "6.0.0"
log = "0.4.11"
multimap = "0.8.2"

# TODO: this is only needed for the bin target
simple_logger = "1.9.0"
